wandb_version: 1

out_dir:
  desc: null
  value: out-shakespeare-char
eval_interval:
  desc: null
  value: 250
log_interval:
  desc: null
  value: 10
eval_iters:
  desc: null
  value: 2
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: false
init_from:
  desc: null
  value: scratch
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: shakespeare-char
wandb_run_name:
  desc: null
  value: mini-gpt
dataset:
  desc: null
  value: shakespeare_char
gradient_accumulation_steps:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 12
block_size:
  desc: null
  value: 128
n_layer:
  desc: null
  value: 8
n_head:
  desc: null
  value: 4
n_embd:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
max_iters:
  desc: null
  value: 2000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 100
lr_decay_iters:
  desc: null
  value: 2000
min_lr:
  desc: null
  value: 0.0001
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: false
pos_enc_type:
  desc: null
  value: orijinal
model_type:
  desc: null
  value: GPT
attention_type:
  desc: null
  value: causal
max_time_minutes:
  desc: null
  value: 0
disable_attn:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694210784.016779
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      6: 4.31.0
      8:
      - 3
      - 5
