wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694339248.48316
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 3
      - 5
